// Exact three-letter prefix vocabulary supplied for Chunk Word Keyboard 2.
// Do not infer or add entries; the section marker identifies each starting letter.
const SOURCE = String.raw`Q qab qad qan qat qep qib qin qis qiv qop qua qub que qui quo qur qwe
W wab wac wad wae waf wag wah wai wak wal wam wan wap war was wat wau wav waw wax way waz wea web wec wed wee wef wei wej wek wel wen wep wer wes wet wha whe whi who whu why wic wid wie wif wig wik wil wim win wip wir wis wit wiv wiz woa wob wod woe wof wog wok wol wom won woo wop wor wos wot wou wov wow wra wre wri wro wru wry wud wul wun wur wus wut wya wyc wye wyl wyn wyv
E eac eag eal ear eas eat eau eav ebb ebo ebr ebu eca ecb ecc ecd ece ech ecl eco ecp ecr ecs ect ecu ecz eda edd ede edg edh edi eds edu eej eek eel eer eff efs eft ega ege egg egl ego egr egy eic eid eig eik ein eir eis eit eja eje eji eke eki ekp eku ela elb eld ele elf elh eli elk ell elm elo els elu elv ely ema emb emc emd eme emi emm emo emp ems emu ena enc end ene enf eng enh eni enj enk enl enm enn eno enp enq enr ens ent enu env enw enz eob eoc eoh eol eon eos epa epe eph epi epo eps equ era erb ere erg eri erk erl erm ern ero err ers ert eru erv ery esb esc ese esk esn eso esp esq ess est esu eta etc ete eth eti etn eto etu ety euc eud eug euh euk eul eun euo eup eur eus eut eux eva eve evi evo evu evz ewe eww exa exc exe exf exh exi exo exp exq exs ext exu eya eye eyi eyo eyr
R rab rac rad raf rag rah rai raj rak ral ram ran rap rar ras rat rau rav raw rax ray raz rea reb rec red ree ref reg reh rei rej rek rel rem ren reo rep req rer res ret reu rev rew rex rey rez rha rhe rhi rho rhu rhy ria rib ric rid rie rif rig rij ril rim rin rio rip ris rit riv rix riy roa rob roc rod roe rog roi rol rom ron roo rop roq ror ros rot rou rov row roy roz rua rub ruc rud rue ruf rug rui rul rum run rup rur rus rut rya rye ryo
T taa tab tac tad tae taf tag tah tai taj tak tal tam tan tao tap taq tar tas tat tau tav taw tax tay taz tch tea teb tec ted tee tef teg teh tei tek tel tem ten teo tep teq ter tes tet teu tev tex tha the thi tho thr thu thw thy tia tib tic tid tie tif tig tik til tim tin tip tir tis tit tix tiy tiz tja tla tme toa tob toc tod toe tof tog toh toi tok tol tom ton too top toq tor tos tot tou tov tow tox toy tra tre tri tro tru try tsa tse tsh tsi tsk tso tsu tua tub tuc tuf tug tui tul tum tun tup tuq tur tus tut tux tuy twa twe twi two tyc tye tyg tyi tyk tyl tym tyn typ tyr tyy tza tze tzi tzu
Y yaa yab yac yad yag yah yak yam yan yap yar yas yat yau yaw yay ycl yea yeb yec yeg yel yen yeo yep yer yes yet yeu yew yid yie yik yin yip yla yle yob yod yog yoh yoi yok yol yom yon yoo yor yot you yow ype ytt yua yuc yug yuk yul yum yup yur yut ywi
U uak ubi ubu udd udo ufo uga ugh ugl ugs uhl uhu uin uit uja uka uke uku ula ulc ule ull ulm uln ulo ulp uls ult ulu ulv uma umb ume umf umi uml umm ump una unb unc und une unf ung unh uni unj unk unl unm unn uno unp unq unr uns unt unu unv unw uny unz upa upb upc upd upe upf upg uph upk upl upm upo upp upr ups upt upw ura urb urc urd ure urg uri urn uro urp urs urt uru usa use ush usi usn usq ust usu ute uti utm uto utr uts utt uva uve uvu uxo uza
I iam iat ibe ibi ibo ibu ice ich ici ick ico ict icy ide idi idl ido ids idy iff ifs igg igl ign igu ihr iiw ijo ika ike iko ila ile ili ilk ill ilm ima imb imi imm imp ina inb inc ind ine inf ing inh ini inj ink inl inm inn ino inp inq inr ins int inu inv inw iny iod iol ion iot ipe ipo ipp ipr ips ira ire iri irk iro irr isa isb isc ise ish isi isl ism isn iso iss ist ita itc ite ith iti its itt ive ivi ivo ivy iwi ixi ixo ixt iza izb izi izz
O oaf oak oar oas oat oba obb obc obd obe obf obi obj obl obm obn obo obr obs obt obu obv oca occ oce och ock oco ocr oct ocu oda odd ode odi odo ods ody oec oed oei oen oer oes oeu ofa off oft oga ogd oge ogh ogi ogl ogo ogr ohe ohi ohm oho ohs oid oik oil oin oit oka oke okr okt old ole olf oli oll olo oly oma omb ome omi omm omn omo omp oms ona onb onc one ong oni onl ono onr ons ont onu onw ony ooc ood oof oog ooh ool oom oop oos oot ooz opa opc ope oph opi opo opp ops opt opu oqu ora orb orc ord ore orf org ori orl orm orn oro orp orr ors ort ory orz osa osc osi osm osn osp oss ost ota oth oti oto ott oua oub ouc oud oue oug oun oup our ous out ouz ova ove ovi ovo ovu owe owi owl own owt oxa oxb oxc oxe oxf oxh oxi oxl oxo oxp oxt oxy oye oys oza ozo
P paa pab pac pad pae pag pah pai paj pak pal pam pan pap par pas pat pau pav paw pax pay paz pea peb pec ped pee peg peh pei pej pek pel pem pen peo pep per pes pet pew pey pfe pff pfu pha phe phi phl pho phr pht phu phw phy pia pib pic pid pie pif pig pii pik pil pim pin pio pip piq pir pis pit piu piv pix piz pla ple pli plo plu ply pne poa pob poc pod poe pog poi pok pol pom pon poo pop por pos pot pou pov pow pox poz pra pre pri pro pru pry psa psc pse psh psi pso pss pst psy pta pte pti pto ptu pty pub puc pud pue puf pug pui puj puk pul pum pun pup pur pus put puz pwn pya pyc pye pyg pyj pyk pyl pyo pyr pyt pyu pyx pza
A aah aal aar aas aba abb abc abd abe abf abh abi abj abl abm abn abo abr abs abu abv abw aby aca acc ace ach aci ack acl acm acn aco acq acr act acu acy ada add ade adh adi adj adm adn ado adr ads adu adv adw ady adz aec aed aeg aen aeo aep aeq aer aes aet afa afe aff afg afi afl afo afr aft aga agb age agg agh agi agl agm agn ago agr ags agu aha ahc ahe ahh ahi aho ahs aib aid aig aik ail aim ain aio air ais ait aja aju aka ake aki akr akv ala alb alc ald ale alf alg alh ali alk all alm aln alo alp alr als alt alu alv alw aly ama amb ame ami amm amn amo amp amr amt amu amy ana anc and ane anf ang anh ani ank anl ann ano ans ant anu anv anx any aor aou apa ape aph api apl apn apo app apr aps apt apy aqu ara arb arc ard are arf arg arh ari ark arm arn aro arp arq arr ars art aru arv ary asa asb asc asd ase ash asi ask asl aso asp asq ass ast asu asw asy ata ate ath ati atl atm ato atr att atw aty aub auc aud aug auk aul aum aun aur aus aut aux ava ave avg avi avo avu awa awe awf awh awi awk awl awn awo awr axe axi axl axm axo axs aya aye ayi ays ayu aza aze azi azl azo azu azy
S saa sab sac sad sae saf sag sah sai sak sal sam san sap sar sas sat sau sav saw sax say sca sce sch sci scl sco scr scu scy sea seb sec sed see seg sei sej sel sem sen sep seq ser ses set sev sew sex sfe sfo sfu sgr sha she shh shi shk shl shm shn sho shp shr sht shu shv shw shy sia sib sic sid sie sif sig sik sil sim sin sip sir sis sit siw six siz sja ska ske ski skl sko sku sky sla sle sli slo slu sly sma sme smi smo smr smu sna sne sni sno snu sny soa sob soc sod soe sof sog soh soi soj sok sol som son soo sop sor sos sot sou sov sow sox soy soz spa spe sph spi spl spo spr spu spy squ sri ssh sta ste sth sti sto str stu sty sua sub suc sud sue suf sug sui suk sul sum sun suo sup suq sur sus sut suz sve swa swe swi swo swu syb syc sye syl sym syn syp syr sys syz sza
D daa dab dac dad dae daf dag dah dai dak dal dam dan dap dar das dat dau dav daw day daz dea deb dec ded dee def deg deh dei dej dek del dem den deo dep deq der des det deu dev dew dex dey dha dho dhu dia dib dic did die dif dig dih dik dil dim din dio dip diq dir dis dit diu div diw dix diz dje dji doa dob doc dod doe dof dog doh doi doj dol dom don doo dop dor dos dot dou dov dow dox doy doz dra dre dri dro dru dry dua dub duc dud due duf dug duh dui duk dul dum dun duo dup dur dus dut duu duv dux duy dva dwa dwe dwi dya dyb dye dyi dyk dyn dys dyt dzi dzo
F fab fac fad fae faf fag fah fai faj fak fal fam fan faq far fas fat fau fav faw fax fay faz fea feb fec fed fee feh fei fel fem fen feo fer fes fet feu fev few fey fez fia fib fic fid fie fif fig fil fim fin fio fip fir fis fit fiv fix fiz fje fjo fla fle fli flo flu fly foa fob foc fod foe fog foh foi fol fom fon foo fop for fos fou fov fow fox foy fra fre fri fro fru fry fub fuc fud fue fuf fug fuh fuj ful fum fun fur fus fut fuz fyc fyk fyl fyr
G gab gad gae gaf gag gah gai gal gam gan gao gap gar gas gat gau gav gaw gay gaz gea geb gec ged gee gef geg gei gel gem gen geo ger ges get geu gev gew gey gha ghe ghi gho ghy gia gib gid gie gif gig gil gim gin gip gir gis git giv giz gla gle gli glo glu gly gme gna gne gno gnu goa gob god goe gof gog goi gol gom gon goo gop gor gos got gou gov gow goy gra gre gri gro gru gua gub guc gud gue guf gug gui gul gum gun gup gur gus gut guv guy guz gwe gwi gyb gym gyn gyo gyp gyr gyt gyv
H haa hab hac had hae haf hag hah hai haj hak hal ham han hao hap har has hat hau hav haw hay haz hea heb hec hed hee hef heg heh hei hej hek hel hem hen hep her hes het heu hev hew hex hey hia hib hic hid hie hig hij hik hil him hin hip hir his hit hiv hiy hiz hmm hoa hob hoc hod hoe hog hoi hok hol hom hon hoo hop hor hos hot hou hov how hoy hry hua hub huc hud hue huf hug huh hui hul hum hun hup hur hus hut huz hwa hwy hya hyb hyd hye hyg hyi hyl hym hyo hyp hyr hys
J jab jac jad jae jag jai jak jal jam jan jap jar jas jat jau jav jaw jay jaz jea jeb jee jef jeh jej jel jem jen jeo jeq jer jes jet jeu jew jez jhe jhi jia jib jic jif jig jih jik jil jim jin jip jis jit jiu jiv jna joa job joc jod joe jog joh joi joj jok jol jon joo jor jos jot jou jov jow joy jub jud jug jui juj juk jul jum jun jup jur jus jut juv jux jyn
K kab kac kad kae kaf kag kah kai kaj kak kal kam kan kao kap kar kas kat kau kav kay kaz kea keb kec ked kee kef keg kei kel kem ken kep ker kes ket kev kew kex key kha khe khi kho khu kia kib kic kid kie kif kik kil kim kin kio kip kir kis kit kiv kiw kje kla kle kli klo klu kly kna kne kni kno knu koa kob koe kof koh koi koj kok kol kom kon koo kop kor kos kot kou kow kra kre kri kro kru kry kuc kud kug kuk kul kum kun kur kuv kva kve kwa kwe kya kyb kye kyl kym kyp kyr kyt
L laa lab lac lad lae laf lag lah lai lak lal lam lan lao lap laq lar las lat lau lav law lax lay laz lea leb lec led lee lef leg leh lei lek lem len leo lep les let leu lev lew lex ley lez lhe lia lib lic lid lie lif lig lik lil lim lin lio lip liq lir lis lit liv lix liz lla loa lob loc lod loe lof log loi lol lom lon loo lop loq lor los lot lou lov low lox loy loz lua lub luc lud lue luf lug luk lul lum lun lup lur lus lut luv lux lwe lya lyc lyd lye lyi lym lyn lyo lyr lys lyt
Z zab zac zad zaf zag zai zak zam zan zap zar zas zax zay zaz zea zeb zec zed zee zei zek zel zem zen zeo zep zer zes zet zeu zho zib zid zig zik zil zin zip zir zit ziz zlo zoa zoc zod zoe zof zoi zol zom zon zoo zor zos zou zow zoy zuc zug zuz zwi zyd zyg zym zyz zzz
X xan xeb xen xer xip xis xoa xyl xys
C cab cac cad cae caf cag cah cai caj cak cal cam can cao cap car cas cat cau cav caw cay cea cec ced cee cef ceg cei cel cem cen ceo cep cer ces cet cev cha che chi chl cho chr cht chu chy cia cib cic cid cie cig cil cim cin cio cip cir cis cit civ cla cle cli clo clu cly cni coa cob coc cod coe cof cog coh coi coj cok col com con coo cop coq cor cos cot cou cov cow cox coy coz cra cre cri cro cru crw cry csa cte cua cub cuc cud cue cuf cui cuk cul cum cun cup cur cus cut cuv cwm cwt cya cyb cyc cyd cyg cyl cym cyn cyp cyr cys cyt cza
V vac vad vag vah vai vak val vam van vap vaq var vas vat vau vav vaw vea vec ved vee veg veh vei vel ven ver ves vet vex via vib vic vid vie vig vik vil vim vin vio vip vir vis vit viv vix viy viz vle vlo voc vod voe vog voi vol vom von voo vor vot vou vow vox voy vra vro vug vul vum vuv vyi
B baa bab bac bad bae baf bag bah bai baj bak bal bam ban bao bap bar bas bat bau bav baw bay baz bde bea beb bec bed bee bef beg beh bei bej bel bem ben bep beq ber bes bet bev bew bey bez bha bhi bia bib bic bid bie bif big bij bik bil bim bin bio bip biq bir bis bit biu biv biw biy biz bla ble bli blo blu boa bob boc bod boe bof bog boh boi bok bol bom bon boo bop bor bos bot bou bov bow box boy boz bra bre bri bro brr bru bry bua bub buc bud buf bug buh bui bul bum bun buo bup buq bur bus but bux buy buz bwa byc bye byg byl byn byp byr bys byt byw byz
N naa nab nac nad nae naf nag nah nai nak nal nam nan nao nap nar nas nat nau nav naw nay naz ndu nea neb nec ned nee nef neg nei nek nel nem nen neo nep ner nes net neu nev new nex ngo ngu ngw nia nib nic nid nie nif nig nih nik nil nim nin nio nip niq nir nis nit niv nix niz nko nob noc nod noe nog noh noi nol nom non noo nop nor nos not nou nov now nox noy noz nth nua nub nuc nud nuf nug nui nuk nul num nun nup nur nus nut nux nuz nya nyb nyc nye nyl nym nys
M maa mab mac mad mae maf mag mah mai maj mak mal mam man map maq mar mas mat mau mav maw max may maz mba mbi mea meb mec med mee meg meh mei mel mem men meo mep mer mes met meu mew mez mhm mho mia mic mid mie mif mig mih mik mil mim min mio miq mir mis mit mix miz mka mmm mne moa mob moc mod mof mog moh moi moj mok mol mom mon moo mop moq mor mos mot mou mov mow mox moz mpr mri muc mud mue muf mug muj muk mul mum mun muo mup mur mus mut muu mux muz mwa mwe mya myc myd mye myi myl myn myo myr mys myt myx mze`;

export const CHUNK_KEYBOARD_THREE_LETTER_PREFIXES = Object.freeze(Object.fromEntries(
  SOURCE.split("\n").map((line) => {
    const [initial, ...prefixes] = line.trim().split(/\s+/u);
    const letter = initial.toLocaleLowerCase("en-US");
    if (!/^[A-Z]$/u.test(initial) || !prefixes.length || prefixes.some((value) => !new RegExp(`^${letter}[a-z]{2}$`, "u").test(value))) {
      throw new Error(`Invalid supplied three-letter prefix section: ${initial}`);
    }
    return [letter, Object.freeze(prefixes)];
  }),
));

export const CHUNK_KEYBOARD_THREE_LETTER_SET = new Set(
  Object.values(CHUNK_KEYBOARD_THREE_LETTER_PREFIXES).flat(),
);
