import assert from 'node:assert/strict';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fixture,parse} from '../tools/local-evaluation.mjs';
const assets=new URL('../assets/',import.meta.url),source=new URL('../semantic/',import.meta.url);
const hash=b=>createHash('sha256').update(b).digest('hex');
async function indexBytes(dir){let n=0;for(const e of await readdir(new URL(dir+"/",assets),{recursive:true,withFileTypes:true})){if(e.isFile())n+=(await readFile(new URL(e.parentPath.split("/relay/assets/")[1]+"/"+e.name,assets))).length;}return n;}
async function load(dir){const manifest=JSON.parse(await readFile(new URL(dir+'/manifest.json',assets),'utf8'));const words=[];for(const shard of manifest.shards){const raw=await readFile(new URL(dir+'/'+shard.path,assets));const content=raw.subarray(0,-1);assert.equal(hash(content),shard.sha256);assert.equal(content.length,shard.bytes);const values=JSON.parse(content);assert.equal(values.length,shard.count);words.push(...values);}assert.equal(words.length,manifest.word_count);return {manifest,words};}
const old=await load('semantic-lexicon-hunspell-base-1'),current=await load('semantic-lexicon');
const policy=JSON.parse(await readFile(new URL('lexicon-policy.json',source),'utf8'));
const required=['read','reply','context','preserve','preserves','preserved','preserving','recurse','recurses','recursed','recursing','recursion','clarify','clarifies','clarified','clarifying','word','words','help','helps','helped','helping','us','bottle','bottles','algorithm','algorithms','asynchronous','tokenizer','tokenizers','tokeniser','tokenisers','compiler','parser','executable','communication','communications','café','I',"I'm",'AI','API','IARC','GET','JSON','UTF-8'];
const selected=new Set(current.words.map(w=>w.toLowerCase()));for(const w of required)assert.ok(selected.has(w.toLowerCase()),'Required spelling '+w);
for(const w of Object.keys(policy.exclude_exact))assert.ok(!selected.has(w),'Excluded abbreviation '+w);
for(const w of ['Alice','London','Google'])assert.ok(!current.words.includes(w),'Proper name '+w);
const variants=[];
for(const size of [60,70]){const words=(await readFile(new URL('esdb-'+size+'-words.txt',source),'utf8')).trim().split('\n');const set=new Set(words.map(w=>w.toLowerCase()));variants.push({size,word_forms:words.length,required_missing:required.filter(w=>!set.has(w.toLowerCase()))});}
const memberships=required.map(word=>({word,old:old.words.some(w=>w.toLowerCase()===word.toLowerCase()),current:selected.has(word.toLowerCase())}));
function prefixStats(words){const counts=new Map();for(const w of words){const p=w.toLowerCase().slice(0,2);if(/^\p{L}{2}$/u.test(p))counts.set(p,(counts.get(p)||0)+1);}const a=[...counts.values()].sort((a,b)=>a-b);return {prefixes:a.length,median_candidates:a[Math.floor(a.length/2)],maximum_candidates:a.at(-1),bo:counts.get('bo'),re:counts.get('re')};}
const oldIndexBytes=await indexBytes('semantic-lexicon-hunspell-base-1'),currentIndexBytes=await indexBytes('semantic-lexicon');
const f=await fixture(),samples=[];try{
const root=await f.request('/predictive-keyboard/html/chunk-keyboard-3/',{html:true});assert.equal(root.status,200);let p=parse(root.text,root.url);
async function follow(label){const l=p.links.find(l=>l['aria-label']===label||l.text===label);assert.ok(l,label);const r=await f.request(l.url,{html:true});assert.equal(r.status,200);p=parse(r.text,r.url);}
await follow('Set START to bo');await follow('Add INSIDE tt');await follow('Set END to le');await follow('Add Bottle');assert.equal(p.draft,'Bottle');
// Supplied link paths only; this measures current local HTTP/render cost, not WAN or reasoning speed.
for(const prefix of ['bo','re','con','pre','non']){let view=parse(root.text,root.url);const two=view.links.find(l=>l['aria-label']==='Set START to '+prefix.slice(0,2));assert.ok(two);let r=await f.request(two.url,{html:true});assert.equal(r.status,200);view=parse(r.text,r.url);const link=prefix.length===2?two:view.links.find(l=>l['aria-label']==='Refine START to '+prefix||l['aria-label']==='Set START to '+prefix);assert.ok(link,'Refinement '+prefix);const times=[];let bytes;for(let i=0;i<5;i++){const start=performance.now();r=await f.request(link.url,{html:true});times.push(Math.round(performance.now()-start));assert.equal(r.status,200);bytes=Buffer.byteLength(r.text);}samples.push({prefix,local_http_ms:times,response_bytes:bytes});}
}finally{await f.close();}
const report={evaluation_version:'lexicon-1.0.0',method:'Pinned fully expanded ESDB exports at sizes 60 and 70, identical classification/exact-exclusion policies and Relay additions. Static case-insensitive required-spelling coverage; shard integrity; real ordinary-link bottle path; five local HTTP/render reads per supplied prefix link. Timings include server rendering and loopback transfer, exclude WAN and participant reasoning, and have no causal before/after latency claim.',selected_size:70,reason:'Broader technical vocabulary while retaining frequency-first ordering; size 60 misses tokenizer/tokeniser families in this coverage set.',variants,required_memberships:memberships,old:{lexicon_version:old.manifest.lexicon_version,word_count:old.words.length,all_index_asset_bytes:oldIndexBytes,initial_capital_spellings:old.words.filter(w=>/^\p{Lu}/u.test(w)).length,shard_bytes:old.manifest.shards.reduce((a,s)=>a+s.bytes,0),prefix_candidates:prefixStats(old.words)},current:{lexicon_version:current.manifest.lexicon_version,word_count:current.words.length,all_index_asset_bytes:currentIndexBytes,initial_capital_spellings:current.words.filter(w=>/^\p{Lu}/u.test(w)).length,shard_bytes:current.manifest.shards.reduce((a,s)=>a+s.bytes,0),prefix_candidates:prefixStats(current.words)},excluded_exact:policy.exclude_exact,lookup_samples:samples,limits:'No finite dictionary contains all possible valid spellings. Full inflections can increase candidate counts; SUBTLEX ordering and INSIDE/END filtering remain important. Exact character composition remains independent.'};
await writeFile(new URL('evaluation/lexicon-1.0.0.json',assets),JSON.stringify(report,null,2)+'\n');console.log('Lexicon passed:',current.words.length,'indexed spellings;',required.length,'required forms; bottle path 4 activations.');
