import assert from 'node:assert/strict';
import {render,initialize,read,follow,close} from '../link-browser/browser.mjs';
import {fixture} from '../tools/local-evaluation.mjs';
import {spawn} from 'node:child_process';
import {pages,Presentation,OUTPUT_BYTE_LIMIT} from '../link-browser/presentation.mjs';
import {configureConnectionAttempts,CONNECTION_ATTEMPT_TIMEOUT_MS} from '../link-browser/connection.mjs';
let connectTimeout=250;
const transport={getDefaultAutoSelectFamilyAttemptTimeout:()=>connectTimeout,setDefaultAutoSelectFamilyAttemptTimeout:value=>connectTimeout=value};
assert.equal(configureConnectionAttempts(transport),CONNECTION_ATTEMPT_TIMEOUT_MS);
connectTimeout=2000;assert.equal(configureConnectionAttempts(transport),2000,'existing longer connection allowance remains intact');
const crowded=render('<title>Crowded</title><pre class="draft">Exact  draft\n</pre><h2>Words</h2>'+Array.from({length:700},(_,i)=>`<a href="/pick?cap=secret${i}" aria-label="Add word ${i}">word${i}</a>`).join(''),'https://example.test/',1);
const paged=pages(crowded.view);
assert.ok(paged.length>1,'crowded pages have bounded local output');
assert.ok(paged.every(p=>Buffer.byteLength(JSON.stringify(p))<OUTPUT_BYTE_LIMIT),'each crowded output fits below tool clipping limits');
assert.deepEqual(paged.flatMap(p=>p.sections.flatMap(s=>s.links.map(l=>l.label))),crowded.links.map(l=>l.label),'every supplied link retained in original order');
assert.ok(paged.every(p=>p.draft==='Exact  draft\n'),'exact draft available on every output page');
assert.ok(!JSON.stringify(paged).includes('secret'),'no action capabilities exposed');
const shown=new Presentation();shown.show(crowded.view,1);
assert.throws(()=>shown.requireObserved({name:'word699'}),/not shown/,'hidden output links cannot be followed');
shown.show(crowded.view,1,paged.length-1);shown.requireObserved({name:'Add word 699',section:'Words'});
shown.show(crowded.view,2);assert.throws(()=>shown.requireObserved({name:'word699'}),/not shown/,'navigation invalidates previously presented choices');
assert.throws(()=>shown.show(crowded.view,2,-1),/Unknown output page/);
assert.throws(()=>pages({sections:[{heading:'Oversize',text:['x'.repeat(OUTPUT_BYTE_LIMIT+1000)],links:[]}]}),error=>error.failureClass==='client-output-overflow','unexpected oversized content fails explicitly instead of silently clipping');
const sample=render('<title>Example</title><h1>Keyboard</h1><p>Notice <a href="/about">About</a></p><form><input name="q"><button>Search</button></form><pre class="draft">A  B\n&lt;x&gt;</pre><h2>Words</h2><a href="/pick?cap=secret">help</a><script>bad()</script>','https://example.test/',1);
assert.equal(sample.view.draft,'A  B\n<x>');assert.equal(sample.links.length,2);assert.ok(!JSON.stringify(sample.view).includes('secret'));assert.ok(!JSON.stringify(sample.view).includes('bad()'));assert.equal(sample.view.sections.at(-1).links[0].label,'help');
let requests=0;const fetcher=async()=>{requests++;return new Response('<h1>Page</h1><p><a href="#words">Words</a></p><a href="/next">Next</a>');};
const fake=await initialize({home:'https://example.test/',fetcher});
const replBrowser=await initialize({home:'https://example.test/',fetcher:async()=>new Response('<h1>Process</h1>')});
const child=spawn(process.execPath,['relay/link-browser/repl.mjs',replBrowser],{stdio:['pipe','pipe','pipe']});let processOutput='';child.stdout.on('data',d=>processOutput+=d);child.stdin.end('{"action":"type","name":"typed field value"}\n');await new Promise(r=>child.once('exit',r));assert.ok(processOutput.includes('Only read and follow are available.'),'persistent browser refuses field input');assert.ok(processOutput.includes('remainingSeconds'),'persistent process supplies the actual clock');assert.ok(processOutput.includes('\"current\"'),'completed errors return the retained page');assert.ok(processOutput.includes('empty polling will not retry'),'recovery distinguishes completed errors from pending output');await assert.rejects(read(replBrowser),/ENOENT/,'closed process deletes private navigation state');
const crowdedId=await initialize({home:'https://example.test/',fetcher:async()=>new Response('<h2>Words</h2>'+Array.from({length:700},(_,i)=>`<a href="/pick?cap=secret${i}">word${i}</a>`).join(''))});
const pagedChild=spawn(process.execPath,['relay/link-browser/repl.mjs',crowdedId],{stdio:['pipe','pipe','pipe']});let pagedOutput='';pagedChild.stdout.on('data',d=>pagedOutput+=d);
pagedChild.stdin.end('{"action":"follow","name":"word699"}\n{"action":"read","page":1}\n{"action":"read","page":-1}\n');
await new Promise(r=>pagedChild.once('exit',r));
const responses=pagedOutput.trim().split('\n').map(line=>JSON.parse(line));
assert.match(responses[1].error,/not shown/,'REPL refuses hidden-page selection before navigation');
assert.equal(responses[2].outputPage,1,'REPL permits bounded local page inspection');
assert.match(responses[3].error,/Unknown output page/);
assert.ok(responses.every(response=>Buffer.byteLength(JSON.stringify(response))<OUTPUT_BYTE_LIMIT),'normal and retained-error output remain bounded');
assert.ok(!pagedOutput.includes('secret'),'REPL never exposes capability URLs');
try {let page=await read(fake);assert.ok(page.remainingSeconds>0&&page.remainingSeconds<=420,'client displays actual remaining time');const fragment=page.sections.flatMap(s=>s.links).find(l=>l.label==='Words');await follow(fake,fragment.id,{fetcher});assert.equal(requests,1,'fragments do not create HTTP requests');await assert.rejects(follow(fake,fragment.id,{fetcher}),/Stale/);assert.equal(requests,1,'stale handle never performs an action');await assert.rejects(follow(fake,'https://example.test/next',{fetcher}),/Stale/);assert.equal(requests,1,'constructed URL cannot be followed');await follow(fake,{name:'Next'},{fetcher});assert.equal(requests,2,'semantic selection follows exactly the supplied link');await assert.rejects(follow(fake,{name:'invented'},{fetcher}),/unknown/);assert.equal(requests,2,'unknown name performs no request');}finally{await close(fake);}
const service=await fixture();let browser;
const failureBrowser=await initialize({home:'https://example.test/',fetcher:async()=>new Response('<pre class="draft">kept</pre><a href="/next">Next</a>')});
try {
  await assert.rejects(follow(failureBrowser,{name:'Next'},{fetcher:async()=>new Response('Worker exceeded resource limits: 1102',{status:503})}),/HTTP 503.*1102/);
  const preserved=await read(failureBrowser);assert.equal(preserved.draft,'kept');assert.equal(preserved.sections.flatMap(s=>s.links)[0].label,'Next');
  let fetchAttempts=0;
  await assert.rejects(follow(failureBrowser,{name:'Next'},{fetcher:async()=>{fetchAttempts++;throw Error('simulated connection failure');}}),error=>error.failureClass==='network-no-response');
  assert.equal(fetchAttempts,1,'failed mutation is never retried automatically');
  assert.equal((await read(failureBrowser)).draft,'kept','network failure preserves exact draft');
  await assert.rejects(follow(failureBrowser,{name:'Next'},{fetcher:async()=>({status:200,headers:new Headers(),text:async()=>{throw Error('interrupted response');}})}),error=>error.failureClass==='network-incomplete-response');
  assert.equal((await read(failureBrowser)).draft,'kept','interrupted successful response does not claim applied action or discard prior page');
  const recovered=await follow(failureBrowser,{name:'Next'},{fetcher:async()=>new Response('<pre class="draft">recovered</pre>')});assert.equal(recovered.draft,'recovered','explicit replay can recover through the original supplied link');
}finally{await close(failureBrowser);}
try {
 browser=await initialize({home:service.base+'/'});
 const choose=async label=>{const p=await read(browser);const l=p.sections.flatMap(s=>s.links).find(l=>l.label===label);assert.ok(l,'missing supplied '+label);return follow(browser,l.id);};
 let p=await choose('Chunk Word Keyboard');assert.equal(p.usage,'recorded');p=await choose('Can');assert.equal(p.draft,'Can');
 const chunkPages=pages(p);assert.ok(chunkPages.every(page=>Buffer.byteLength(JSON.stringify(page))<OUTPUT_BYTE_LIMIT),'actual Chunk output fits bounded transport');
 assert.equal(chunkPages.flatMap(page=>page.sections.flatMap(section=>section.links)).length,p.sections.flatMap(section=>section.links).length,'actual Chunk retains all supplied choices');
 p=await choose('Review message');assert.equal(p.draft,'Can');assert.ok(p.sections.flatMap(s=>s.links).some(l=>l.label==='Cancel this review and continue editing'));
 p=await choose('Cancel this review and continue editing');assert.ok(p.sections.some(s=>s.text.some(t=>t.includes('Your composition is preserved'))));
 p=await choose('Edit message');assert.equal(p.draft,'Can','review cancellation returns to exact composition through supplied links');
 assert.equal((await service.request('/poll')).body.returned_count,0,'cancelling a review does not publish');
 console.log('Link-only browser: literal draft rendering, supplied handles only, stale-link rejection, fragment semantics and live cancellation recovery passed.');
}finally {if(browser)await close(browser);await service.close();}
